var content = '# Markdown Previewer \n'
              + '## Type in the text area...\n'
              + '### ...to experiment with Markdown\n'
              + '\n'
              + 'Paragraphs are separated by a blank line.\n'
              + '\n'
              + 'Leave 2 spaces at the end of a line to do a  \nline break\n'
              + '\n'
              + 'Text attributes *italic*, **bold**, `monospace`, ~~strikethrough~~.\n'
              + '\n'
              + 'Unordered list:\n'
              + '\n'
              + '* apples\n'
              + '* oranges\n'
              + '* pears\n'  
              + '\n'
              + 'Ordered list:\n'
              + '\n'
              + '1. apples\n'
              + '2. oranges\n'
              + '3. pears\n'  
              + '\n'
              + '---\n'
              + '#### Created by:\n'
              + '\n'
	       + '[John Callahan](https://github.com/johnwcallahan)';

module.exports = content;